language: "node_js"

node_js:
  - "10.1.0"

sudo: false

services:
  - mongodb

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - yarn test

cache:
  yarn: true
  directories:
    - "node_modules"
